title: DefensX
description: DefensX protects users from sophisticated cybersecurity attacks by isolating threats from reaching end-point devices, such as desktops, laptops, smart phones and tablets.
author: DefensX Team
email: info@defensx.com
baseurl: "/defensx_test"
url: "http://localhost:4000"
theme: minima
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll/minibundle

nav:
  - title: Solutions
    url: /solutions/
    submenu:
      - title: Endpoint Protection
        url: /solutions/endpoint-protection/
      - title: Content Filtering
        url: /solutions/content-filtering/
      - title: DNS Security
        url: /solutions/dns-security/
      - title: Remote Browser Isolation
        url: /solutions/remote-browser-isolation/
      - title: Data Loss Prevention
        url: /solutions/data-loss-prevention/
      - title: Credential & Identity Theft
        url: /solutions/credential-identity-theft/
      - title: Ad Blocking
        url: /solutions/ad-blocking/
      - title: AI-Powered Reports
        url: /solutions/ai-powered-reports/
  - title: For MSPs
    url: /msps/
  - title: For Enterprises
    url: /enterprises/
  - title: Product
    url: /product/
  - title: Resource
    url: /resources/
  - title: Get in Touch
    url: /contact/

gems:
  - jekyll-paginate
  - jekyll-assets
  - jekyll-minibundle

minibundle:
  - assets:
    - "assets/js/main.js"
    - "assets/css/style.css"

include:
  - "/defensx_test/assets/animations/DefensX_Side_BY_Side_Animation_V2.json"
  - "/defensx_test/assets/animations/DefensX_Mobile_Animation_V2.json"