title: DefensX
description: DefensX protects users from sophisticated cybersecurity attacks by isolating threats from reaching end-point devices, such as desktops, laptops, smart phones and tablets.
author: DefensX Team
email: info@defensx.com
baseurl: "/defensx_test"
url: "http://localhost:4000"
theme: minima
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll/minibundle

nav:
  - title: Solutions
    url: /solutions/
    submenu:
      - title: Credential & Identity Theft
        url: /solutions/credential-identity-theft/
      - title: AI-Agent Protection
        url: /solutions/ai-agent-protection/
      - title: AI Threat Intelligence Reports
        url: /solutions/ai-threat-intelligence-reports/  
      - title: Content Filtering
        url: /solutions/content-filtering/  
      - title: DNS Security
        url: /solutions/dns-security/  
      - title: Secure Web Browser
        url: /solutions/secure-web-browser/  
      - title: Remote Browser Isolation
        url: /solutions/remote-browser-isolation/
      - title: Data Loss Protection
        url: /solutions/data-loss-protection/
  - title: For MSPs
    url: /security-for-msps/
  - title: For Enterprises
    url: /security-for-enterprises/
  - title: Product
    url: /product/
  - title: Resource
    url: /resources/
  - title: Get in Touch
    url: /contact/

gems:
  - jekyll-paginate
  - jekyll-assets
  - jekyll-minibundle

minibundle:
  - assets:
    - "assets/js/main.js"
    - "assets/css/style.css"

include:
  - _pages
  - "/defensx_test/assets/animations/DefensX_Side_BY_Side_Animation_V3.json"
  - "/defensx_test/assets/animations/DefensX_Mobile_Animation_V2.json"
  - "robots.txt"